-- =============================================================================
-- 0031_mastery_telemetry — DOMINIO POR CONCEPTO + TELEMETRÍA append-only
-- (Master Plan §3.2 fila 0031, §3.4 motor, §3.5 un solo camino de escritura).
--
-- Cierra el loop de aprendizaje: cada intento YA VALIDADO mueve el theta del
-- concepto con el MISMO Elo unitario probado en src/lib/diagnostic.ts (eloStep),
-- programa repaso espaciado (HLR) y hace rollup a user_skills.mastery (columna
-- huérfana de 0007). Toda escritura pasa por RPC SECURITY DEFINER service_role-only
-- (patrón 0023); el cliente nunca decide dominio ni XP.
--
-- ADITIVO y RETROCOMPATIBLE: tablas/RPC nuevas con IF NOT EXISTS / OR REPLACE;
-- nada del esquema actual cambia. DEGRADACIÓN ELEGANTE: con user_concept_mastery
-- vacío, apply_lesson_attempts solo escribe telemetría y devuelve 0 cruces => el
-- orquestador paga solo XP de Esfuerzo (no-op de dominio).
--
-- Resolución de conceptos: el JSONB de contenido referencia por SLUG estable; las
-- RPC aceptan slug O uuid y resuelven contra concepts (0028).
-- =============================================================================

-- ── 0) Helpers puros (IMMUTABLE) compartidos por las RPC ─────────────────────
-- Banda de dominio derivada de theta vs dificultad del concepto (CEFR 1–6).
-- Espeja la noción de "Encantamiento" del plan: aprendiendo < competente < dominado.
CREATE OR REPLACE FUNCTION public._mc_mastery_band(p_theta REAL, p_difficulty REAL)
RETURNS TEXT LANGUAGE sql IMMUTABLE AS $$
  SELECT CASE
    WHEN p_theta >= COALESCE(p_difficulty, 3.0) + 0.5 THEN 'dominado'
    WHEN p_theta >= COALESCE(p_difficulty, 3.0) - 0.5 THEN 'competente'
    ELSE 'aprendiendo' END;
$$;

-- % de dominio para UI/rollup: masteryPct = round(clamp((theta-1)/5,0,1)*100).
CREATE OR REPLACE FUNCTION public._mc_mastery_pct(p_theta REAL)
RETURNS INT LANGUAGE sql IMMUTABLE AS $$
  SELECT GREATEST(0, LEAST(100, round(((p_theta - 1) / 5.0) * 100)))::int;
$$;

-- Rango ordinal de banda (para detectar CRUCES hacia arriba = pago de Encantamiento).
CREATE OR REPLACE FUNCTION public._mc_band_rank(p_band TEXT)
RETURNS INT LANGUAGE sql IMMUTABLE AS $$
  SELECT CASE p_band WHEN 'dominado' THEN 2 WHEN 'competente' THEN 1 ELSE 0 END;
$$;

-- =============================================================================
-- 1) user_concept_mastery — dominio por (usuario, concepto): theta (Elo) + HLR
--    (half-life regression) para repaso espaciado. PK compuesta = una fila por par.
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.user_concept_mastery (
  user_id         UUID NOT NULL REFERENCES public.users(id)    ON DELETE CASCADE,
  concept_id      UUID NOT NULL REFERENCES public.concepts(id) ON DELETE CASCADE,
  theta           REAL NOT NULL DEFAULT 3.0,     -- habilidad CEFR 1–6 (mismo eje que difficulty)
  attempts        INT  NOT NULL DEFAULT 0,
  correct         INT  NOT NULL DEFAULT 0,
  half_life_hours REAL NOT NULL DEFAULT 4,        -- vida media de memoria (HLR)
  last_seen_at    TIMESTAMPTZ,
  next_review_at  TIMESTAMPTZ,                    -- due de repaso (= last_seen + half_life)
  band            TEXT,                           -- aprendiendo | competente | dominado
  PRIMARY KEY (user_id, concept_id)
);
CREATE INDEX IF NOT EXISTS user_concept_mastery_due_idx
  ON public.user_concept_mastery(user_id, next_review_at);

ALTER TABLE public.user_concept_mastery ENABLE ROW LEVEL SECURITY;
-- Lectura propia para el alumno; la escritura es exclusiva de service_role (vía RPC).
REVOKE ALL ON public.user_concept_mastery FROM anon;
GRANT SELECT ON public.user_concept_mastery TO authenticated;
GRANT ALL    ON public.user_concept_mastery TO service_role;
DROP POLICY IF EXISTS "ucm self" ON public.user_concept_mastery;
CREATE POLICY "ucm self" ON public.user_concept_mastery
  FOR SELECT TO authenticated USING (user_id = auth.uid());

-- =============================================================================
-- 2) exercise_attempts — TELEMETRÍA append-only (un solo camino de escritura).
--    Cada intento validado se inserta aquí; jamás se actualiza/borra.
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.exercise_attempts (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       UUID NOT NULL REFERENCES public.users(id)      ON DELETE CASCADE,
  activity_id   UUID          REFERENCES public.activities(id)  ON DELETE SET NULL,
  exercise_idx  INT,
  exercise_type TEXT,
  concept_ids   TEXT[]  NOT NULL DEFAULT '{}',   -- slugs (estable); GIN para consultas por concepto
  correct       BOOLEAN,
  response_ms   INT,
  hint_used     BOOLEAN NOT NULL DEFAULT false,
  why_used      BOOLEAN NOT NULL DEFAULT false,
  skipped       BOOLEAN NOT NULL DEFAULT false,
  difficulty    REAL,
  theta_before  REAL,
  theta_after   REAL,
  is_review     BOOLEAN NOT NULL DEFAULT false,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS exercise_attempts_user_time_idx ON public.exercise_attempts(user_id, created_at);
CREATE INDEX IF NOT EXISTS exercise_attempts_concepts_idx  ON public.exercise_attempts USING GIN (concept_ids);

ALTER TABLE public.exercise_attempts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.exercise_attempts FROM anon;
GRANT SELECT ON public.exercise_attempts TO authenticated;
GRANT ALL    ON public.exercise_attempts TO service_role;
DROP POLICY IF EXISTS "attempts self" ON public.exercise_attempts;
CREATE POLICY "attempts self" ON public.exercise_attempts
  FOR SELECT TO authenticated USING (user_id = auth.uid());

-- =============================================================================
-- 3) apply_lesson_attempts — ÚNICO writer de dominio (Plan §3.5 paso 1).
--    Por cada attempt YA VALIDADO por el route (anti-fraude con gradeItem en JS):
--      · inserta en exercise_attempts (telemetría, siempre, aunque no resuelva concepto);
--      · actualiza user_concept_mastery con el MISMO Elo unitario de eloStep
--        (p = 1/(1+10^((d-theta)/1)); k = max(0.15, 0.4·0.9^attempts); clamp 1..6);
--      · HLR: acierto half_life·=2.2 (con tope); fallo reset a 4h;
--        next_review_at = now()+half_life h; last_seen_at = now(); attempts/correct +;
--      · rollup ponderado a user_skills.mastery por destreza (solo si la skill existe).
--    Devuelve {enchantments:[{conceptId,conceptSlug,bandBefore,bandAfter,thetaAfter,
--    crossedUp}], applied:N} con los CRUCES de banda netos del lote (los paga
--    grant_mastery_rewards de F5). service_role-only.
-- =============================================================================
CREATE OR REPLACE FUNCTION public.apply_lesson_attempts(
  p_user UUID, p_activity UUID, p_attempts JSONB)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  att            JSONB;
  v_raw_concept  TEXT;
  v_concept_id   UUID;
  v_concept_diff REAL;
  v_concept_skill TEXT;
  v_concept_slugs TEXT[];
  v_correct      BOOLEAN;
  v_difficulty   REAL;
  v_response_ms  INT;
  v_hint_used    BOOLEAN;
  v_why_used     BOOLEAN;
  v_skipped      BOOLEAN;
  v_is_review    BOOLEAN;
  v_ex_idx       INT;
  v_ex_type      TEXT;
  -- estado de Elo/HLR del concepto
  v_theta        REAL;
  v_attempts     INT;
  v_correct_cnt  INT;
  v_half_life    REAL;
  v_k            DOUBLE PRECISION;
  v_p            DOUBLE PRECISION;
  v_theta_before REAL;
  v_theta_after  REAL;
  v_band_diff    REAL;
  v_band_before  TEXT;
  v_band_after   TEXT;
  -- acumuladores del lote
  v_seen         JSONB := '{}'::jsonb;   -- conceptId(text) -> banda ANTES del lote
  v_skills       TEXT[] := '{}';
  v_applied      INT := 0;
  v_skill        TEXT;
  v_skill_mast   NUMERIC;
  v_events       JSONB;
BEGIN
  IF p_user IS NULL THEN RAISE EXCEPTION 'no user'; END IF;
  IF jsonb_typeof(p_attempts) <> 'array' THEN
    RETURN jsonb_build_object('enchantments', '[]'::jsonb, 'applied', 0);
  END IF;

  FOR att IN SELECT jsonb_array_elements(p_attempts) LOOP
    -- ── Lectura defensiva del attempt ──────────────────────────────────────
    v_correct     := COALESCE((att->>'correct')::boolean, false);
    v_difficulty  := COALESCE((att->>'difficulty')::real, 3.0);
    v_response_ms := NULLIF(att->>'response_ms', '')::int;
    v_hint_used   := COALESCE((att->>'hint_used')::boolean, false);
    v_why_used    := COALESCE((att->>'why_used')::boolean, false);
    v_skipped     := COALESCE((att->>'skipped')::boolean, false);
    v_is_review   := COALESCE((att->>'is_review')::boolean, false);
    v_ex_idx      := NULLIF(att->>'exercise_idx', '')::int;
    v_ex_type     := att->>'exercise_type';
    v_raw_concept := att->>'concept_id';

    -- slugs para telemetría: array explícito si viene, si no el concept_id suelto.
    IF jsonb_typeof(att->'concept_ids') = 'array' THEN
      v_concept_slugs := ARRAY(SELECT jsonb_array_elements_text(att->'concept_ids'));
    ELSIF v_raw_concept IS NOT NULL THEN
      v_concept_slugs := ARRAY[v_raw_concept];
    ELSE
      v_concept_slugs := '{}';
    END IF;

    -- ── Resolver concepto: primero por slug, luego como uuid validado ──────
    v_concept_id := NULL; v_concept_diff := NULL; v_concept_skill := NULL;
    IF v_raw_concept IS NOT NULL THEN
      SELECT id, difficulty, skill INTO v_concept_id, v_concept_diff, v_concept_skill
        FROM public.concepts WHERE slug = v_raw_concept;
      IF v_concept_id IS NULL THEN
        BEGIN
          SELECT id, difficulty, skill INTO v_concept_id, v_concept_diff, v_concept_skill
            FROM public.concepts WHERE id = v_raw_concept::uuid;
        EXCEPTION WHEN others THEN
          v_concept_id := NULL;
        END;
      END IF;
    END IF;

    v_theta_before := NULL; v_theta_after := NULL;

    -- ── Actualización de dominio (solo si el concepto resolvió) ────────────
    IF v_concept_id IS NOT NULL THEN
      SELECT theta, attempts, correct, half_life_hours
        INTO v_theta, v_attempts, v_correct_cnt, v_half_life
        FROM public.user_concept_mastery
       WHERE user_id = p_user AND concept_id = v_concept_id;
      IF NOT FOUND THEN
        v_theta := 3.0; v_attempts := 0; v_correct_cnt := 0; v_half_life := 4;
      END IF;

      v_band_diff    := COALESCE(v_concept_diff, v_difficulty, 3.0);
      v_theta_before := v_theta;
      v_band_before  := public._mc_mastery_band(v_theta_before, v_band_diff);

      -- Elo unitario IDÉNTICO a eloStep (k por defecto del plan).
      v_k := GREATEST(0.15, 0.4 * power(0.9, v_attempts));
      v_p := 1.0 / (1.0 + power(10, (v_difficulty - v_theta) / 1.0));
      v_theta := GREATEST(1, LEAST(6, v_theta + v_k * ((CASE WHEN v_correct THEN 1 ELSE 0 END) - v_p)))::real;

      -- HLR: acierto refuerza la memoria (tope 8760h), fallo la reinicia.
      IF v_correct THEN v_half_life := LEAST(v_half_life * 2.2, 8760)::real;
      ELSE              v_half_life := 4;
      END IF;

      v_band_after  := public._mc_mastery_band(v_theta, v_band_diff);
      v_theta_after := v_theta;

      INSERT INTO public.user_concept_mastery
        (user_id, concept_id, theta, attempts, correct, half_life_hours, last_seen_at, next_review_at, band)
      VALUES
        (p_user, v_concept_id, v_theta, v_attempts + 1,
         v_correct_cnt + (CASE WHEN v_correct THEN 1 ELSE 0 END),
         v_half_life, now(), now() + (v_half_life * interval '1 hour'), v_band_after)
      ON CONFLICT (user_id, concept_id) DO UPDATE SET
        theta           = EXCLUDED.theta,
        attempts        = EXCLUDED.attempts,
        correct         = EXCLUDED.correct,
        half_life_hours = EXCLUDED.half_life_hours,
        last_seen_at    = EXCLUDED.last_seen_at,
        next_review_at  = EXCLUDED.next_review_at,
        band            = EXCLUDED.band;

      -- Registrar banda ANTES del lote (solo la 1ª vez que vemos el concepto).
      IF NOT (v_seen ? v_concept_id::text) THEN
        v_seen := v_seen || jsonb_build_object(v_concept_id::text, v_band_before);
      END IF;
      -- Acumular destreza para el rollup.
      IF v_concept_skill IS NOT NULL THEN
        v_skills := array_append(v_skills, v_concept_skill);
      END IF;
      v_applied := v_applied + 1;
    END IF;

    -- ── Telemetría append-only (SIEMPRE, aunque no resuelva concepto) ──────
    INSERT INTO public.exercise_attempts
      (user_id, activity_id, exercise_idx, exercise_type, concept_ids, correct,
       response_ms, hint_used, why_used, skipped, difficulty, theta_before, theta_after, is_review)
    VALUES
      (p_user, p_activity, v_ex_idx, v_ex_type, v_concept_slugs, v_correct,
       v_response_ms, v_hint_used, v_why_used, v_skipped, v_difficulty, v_theta_before, v_theta_after, v_is_review);
  END LOOP;

  -- ── Rollup ponderado a user_skills.mastery (por destreza tocada) ──────────
  -- Solo si la destreza existe en skills (FK); si no, no-op (degradación segura).
  v_skills := ARRAY(SELECT DISTINCT x FROM unnest(v_skills) AS x WHERE x IS NOT NULL);
  IF array_length(v_skills, 1) IS NOT NULL THEN
    FOREACH v_skill IN ARRAY v_skills LOOP
      SELECT round(
               sum(public._mc_mastery_pct(m.theta) * GREATEST(m.attempts, 1)::numeric)
               / NULLIF(sum(GREATEST(m.attempts, 1)), 0))
        INTO v_skill_mast
        FROM public.user_concept_mastery m
        JOIN public.concepts c ON c.id = m.concept_id
       WHERE m.user_id = p_user AND c.skill = v_skill;

      IF v_skill_mast IS NOT NULL AND EXISTS (SELECT 1 FROM public.skills WHERE id = v_skill) THEN
        INSERT INTO public.user_skills (user_id, skill_id, mastery)
        VALUES (p_user, v_skill, v_skill_mast)
        ON CONFLICT (user_id, skill_id) DO UPDATE SET mastery = EXCLUDED.mastery;
      END IF;
    END LOOP;
  END IF;

  -- ── Cruces de banda NETOS del lote (compara banda inicial vs estado actual) ─
  SELECT COALESCE(jsonb_agg(jsonb_build_object(
           'conceptId',  k.key,
           'conceptSlug', c.slug,
           'bandBefore', k.value,
           'bandAfter',  m.band,
           'thetaAfter', m.theta,
           'crossedUp',  public._mc_band_rank(m.band) > public._mc_band_rank(k.value::text)
         )), '[]'::jsonb)
    INTO v_events
    FROM jsonb_each_text(v_seen) AS k
    JOIN public.concepts c ON c.id = k.key::uuid
    JOIN public.user_concept_mastery m ON m.user_id = p_user AND m.concept_id = k.key::uuid;

  RETURN jsonb_build_object('enchantments', COALESCE(v_events, '[]'::jsonb), 'applied', v_applied);
END;
$$;
REVOKE ALL ON FUNCTION public.apply_lesson_attempts(UUID, UUID, JSONB) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.apply_lesson_attempts(UUID, UUID, JSONB) TO service_role;

-- =============================================================================
-- 4) get_due_reviews — conceptos due (next_review_at <= now) ordenados por
--    'strength' = 2^(-elapsed_horas/half_life) ASCENDENTE (lo más olvidado primero).
--    Lectura: callable por authenticated (solo su propia fila) y service_role.
-- =============================================================================
CREATE OR REPLACE FUNCTION public.get_due_reviews(p_user UUID, p_limit INT DEFAULT 20)
RETURNS TABLE (
  concept_id     UUID,
  slug           TEXT,
  label          TEXT,
  skill          TEXT,
  theta          REAL,
  band           TEXT,
  half_life_hours REAL,
  last_seen_at   TIMESTAMPTZ,
  next_review_at TIMESTAMPTZ,
  strength       DOUBLE PRECISION
) LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  -- Guardia: un authenticated solo puede leer lo suyo; service_role (uid NULL) cualquiera.
  IF auth.uid() IS NOT NULL AND auth.uid() <> p_user THEN
    RAISE EXCEPTION 'forbidden';
  END IF;

  RETURN QUERY
  SELECT m.concept_id, c.slug, c.label, c.skill, m.theta, m.band,
         m.half_life_hours, m.last_seen_at, m.next_review_at,
         power(2, - (extract(epoch FROM (now() - m.last_seen_at)) / 3600.0)
                   / GREATEST(m.half_life_hours, 0.01)) AS strength
    FROM public.user_concept_mastery m
    JOIN public.concepts c ON c.id = m.concept_id
   WHERE m.user_id = p_user
     AND m.next_review_at IS NOT NULL
     AND m.next_review_at <= now()
   ORDER BY strength ASC
   LIMIT GREATEST(COALESCE(p_limit, 20), 1);
END;
$$;
REVOKE ALL ON FUNCTION public.get_due_reviews(UUID, INT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_due_reviews(UUID, INT) TO authenticated, service_role;

-- =============================================================================
-- 5) recommend_next — "siguiente mejor misión" (heurística v1, Plan §3.4/§5.2):
--    (1) deuda de repaso -> (2) destreza más débil -> (3) avance. Devuelve
--    {kind:'review'|'skill'|'advance', concept?, skill?, reason}.
--    Lectura propia (authenticated) o service_role.
-- =============================================================================
CREATE OR REPLACE FUNCTION public.recommend_next(p_user UUID)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_due_cnt  INT;
  v_due      RECORD;
  v_weak     RECORD;
BEGIN
  IF auth.uid() IS NOT NULL AND auth.uid() <> p_user THEN
    RAISE EXCEPTION 'forbidden';
  END IF;

  -- (1) Deuda de repaso: ¿hay conceptos due? -> misión de mantenimiento.
  SELECT count(*) INTO v_due_cnt
    FROM public.user_concept_mastery
   WHERE user_id = p_user AND next_review_at IS NOT NULL AND next_review_at <= now();

  IF COALESCE(v_due_cnt, 0) > 0 THEN
    SELECT m.concept_id, c.slug, c.label, c.skill
      INTO v_due
      FROM public.user_concept_mastery m
      JOIN public.concepts c ON c.id = m.concept_id
     WHERE m.user_id = p_user AND m.next_review_at IS NOT NULL AND m.next_review_at <= now()
     ORDER BY power(2, - (extract(epoch FROM (now() - m.last_seen_at)) / 3600.0)
                       / GREATEST(m.half_life_hours, 0.01)) ASC
     LIMIT 1;
    RETURN jsonb_build_object(
      'kind', 'review',
      'concept', jsonb_build_object('id', v_due.concept_id, 'slug', v_due.slug, 'label', v_due.label, 'skill', v_due.skill),
      'reason', format('Tienes %s repaso(s) por reforzar', v_due_cnt)
    );
  END IF;

  -- (2) Destreza más débil (menor masteryPct medio sobre conceptos con intentos).
  SELECT c.skill AS skill,
         round(avg(public._mc_mastery_pct(m.theta)))::int AS pct
    INTO v_weak
    FROM public.user_concept_mastery m
    JOIN public.concepts c ON c.id = m.concept_id
   WHERE m.user_id = p_user AND c.skill IS NOT NULL AND m.attempts > 0
   GROUP BY c.skill
   ORDER BY pct ASC
   LIMIT 1;

  IF FOUND THEN
    RETURN jsonb_build_object(
      'kind', 'skill',
      'skill', v_weak.skill,
      'reason', format('Tu destreza más débil es %s (%s%%)', v_weak.skill, v_weak.pct)
    );
  END IF;

  -- (3) Avance: sin datos de dominio aún -> seguir la ruta lineal (fallback seguro).
  RETURN jsonb_build_object('kind', 'advance', 'reason', 'Continúa tu aventura');
END;
$$;
REVOKE ALL ON FUNCTION public.recommend_next(UUID) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.recommend_next(UUID) TO authenticated, service_role;

-- =============================================================================
-- 6) backfill_mastery_from_diagnostic — PRIOR de dominio (cold start, Plan §3.4).
--    Por cada concepto sin fila de mastery del usuario, crea una con theta inicial
--    derivado de la última evaluación (category_levels->>'theta', o 3.0) con
--    SHRINKAGE leve hacia el centro de su banda. IDEMPOTENTE: ON CONFLICT DO NOTHING
--    (no pisa filas existentes). Se llama desde /api/placement/finish. service_role-only.
-- =============================================================================
CREATE OR REPLACE FUNCTION public.backfill_mastery_from_diagnostic(p_user UUID)
RETURNS INT LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_eval_theta REAL;
  v_band       INT;
  v_band_ctr   REAL;   -- theta central de la banda: 1 + (band-1)*(5/7)
  v_theta_init REAL;
  v_rows       INT;
BEGIN
  IF p_user IS NULL THEN RAISE EXCEPTION 'no user'; END IF;

  -- Última evaluación del usuario: theta global (proxy de destreza; no hay theta
  -- por skill persistido). Ausente/no numérico => 3.0 default.
  SELECT NULLIF(category_levels->>'theta', '')::real
    INTO v_eval_theta
    FROM public.evaluations
   WHERE user_id = p_user
   ORDER BY created_at DESC
   LIMIT 1;
  v_eval_theta := COALESCE(v_eval_theta, 3.0);

  -- Banda (1–8) inversa de difOf(band)=1+(band-1)*(5/7); centro = ese mismo theta.
  v_band     := GREATEST(1, LEAST(8, round(1 + (v_eval_theta - 1) * (7.0/5.0))::int));
  v_band_ctr := (1 + (v_band - 1) * (5.0/7.0))::real;
  -- Shrinkage leve (0.3) hacia el centro de la banda.
  v_theta_init := GREATEST(1, LEAST(6, v_eval_theta + 0.3 * (v_band_ctr - v_eval_theta)))::real;

  -- Siembra solo conceptos que aún no tienen fila (idempotente).
  INSERT INTO public.user_concept_mastery
    (user_id, concept_id, theta, attempts, correct, half_life_hours, band)
  SELECT p_user, c.id, v_theta_init, 0, 0, 4,
         public._mc_mastery_band(v_theta_init, c.difficulty)
    FROM public.concepts c
  ON CONFLICT (user_id, concept_id) DO NOTHING;
  GET DIAGNOSTICS v_rows = ROW_COUNT;

  RETURN v_rows;
END;
$$;
REVOKE ALL ON FUNCTION public.backfill_mastery_from_diagnostic(UUID) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.backfill_mastery_from_diagnostic(UUID) TO service_role;

-- =============================================================================
-- DOWN: (additive-only; revertir solo en entornos no productivos)
-- DROP FUNCTION IF EXISTS public.backfill_mastery_from_diagnostic(UUID);
-- DROP FUNCTION IF EXISTS public.recommend_next(UUID);
-- DROP FUNCTION IF EXISTS public.get_due_reviews(UUID, INT);
-- DROP FUNCTION IF EXISTS public.apply_lesson_attempts(UUID, UUID, JSONB);
-- DROP TABLE IF EXISTS public.exercise_attempts;
-- DROP TABLE IF EXISTS public.user_concept_mastery;
-- DROP FUNCTION IF EXISTS public._mc_band_rank(TEXT);
-- DROP FUNCTION IF EXISTS public._mc_mastery_pct(REAL);
-- DROP FUNCTION IF EXISTS public._mc_mastery_band(REAL, REAL);
-- (Índices y políticas caen con sus tablas.)
-- =============================================================================
